# :: PR 시 브랜치 전략을 따르도록 구성하기
#    - base는 develop & main으로만 PR 가능
#    - feature는 base로만 PR 가능
name: PR-Branch-Rules

on: 
  pull_request: 
    # PR open 시, 새 커밋 반영 시, reopen 시 해당 github action 동작 -> PR 버튼을 누르기 전에 항상 체크 하도록
    types: [opened, synchronize, reopened] 

jobs:
  check-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch rules
        run: |
          # GitHub에서 제공하는 환경변수로 브랜치 정보 가져오기
          HEAD_BRANCH=${{ github.head_ref }}  # 출발지
          BASE_BRANCH=${{ github.base_ref }}  # 목적지
          
          echo "Pull Request: $HEAD_BRANCH -> $BASE_BRANCH"
          
          # feature 브랜치는 base로만 PR 가능
          if [[ $HEAD_BRANCH == feature/* && $BASE_BRANCH != base ]]; then
            echo "Error: feature 브랜치는 base 브랜치로만 PR을 생성할 수 있습니다."
            exit 1
          fi
          
          # base 브랜치는 develop이나 main으로만 PR 가능
          if [[ $HEAD_BRANCH == base && $BASE_BRANCH != develop && $BASE_BRANCH != main ]]; then
            echo "Error: base 브랜치는 develop 또는 main 브랜치로만 PR을 생성할 수 있습니다."
            exit 1
          fi
          
          echo "브랜치 규칙 검사 통과"
